name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies (backend)
        run: cd backend && npm install --legacy-peer-deps
      - name: Lint code (backend)
        run: cd backend && npm run lint || echo "Lint warnings found"
      - name: Create Jest setup file if missing
        run: |
          cd backend
          mkdir -p src/tests
          if [ ! -f src/tests/setup.js ]; then
            echo "// Jest setup file" > src/tests/setup.js
          fi
      - name: Run Jest tests (backend)
        run: cd backend && npm test
